// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	models "github.com/amerikarno/icoApi/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIOpenAccountsRepository is a mock of IOpenAccountsRepository interface.
type MockIOpenAccountsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOpenAccountsRepositoryMockRecorder
}

// MockIOpenAccountsRepositoryMockRecorder is the mock recorder for MockIOpenAccountsRepository.
type MockIOpenAccountsRepositoryMockRecorder struct {
	mock *MockIOpenAccountsRepository
}

// NewMockIOpenAccountsRepository creates a new mock instance.
func NewMockIOpenAccountsRepository(ctrl *gomock.Controller) *MockIOpenAccountsRepository {
	mock := &MockIOpenAccountsRepository{ctrl: ctrl}
	mock.recorder = &MockIOpenAccountsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOpenAccountsRepository) EXPECT() *MockIOpenAccountsRepositoryMockRecorder {
	return m.recorder
}

// CreateOpenAccount mocks base method.
func (m *MockIOpenAccountsRepository) CreateOpenAccount(columns models.IDCardOpenAccounts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenAccount", columns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOpenAccount indicates an expected call of CreateOpenAccount.
func (mr *MockIOpenAccountsRepositoryMockRecorder) CreateOpenAccount(columns interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenAccount", reflect.TypeOf((*MockIOpenAccountsRepository)(nil).CreateOpenAccount), columns)
}

// MockIExternal is a mock of IExternal interface.
type MockIExternal struct {
	ctrl     *gomock.Controller
	recorder *MockIExternalMockRecorder
}

// MockIExternalMockRecorder is the mock recorder for MockIExternal.
type MockIExternalMockRecorder struct {
	mock *MockIExternal
}

// NewMockIExternal creates a new mock instance.
func NewMockIExternal(ctrl *gomock.Controller) *MockIExternal {
	mock := &MockIExternal{ctrl: ctrl}
	mock.recorder = &MockIExternalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExternal) EXPECT() *MockIExternalMockRecorder {
	return m.recorder
}

// GenUuid mocks base method.
func (m *MockIExternal) GenUuid() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenUuid")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenUuid indicates an expected call of GenUuid.
func (mr *MockIExternalMockRecorder) GenUuid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenUuid", reflect.TypeOf((*MockIExternal)(nil).GenUuid))
}
